# Conformal Prediction for Iris Classification with SVM in R

This project implements conformal prediction techniques (Basic and Adaptive)
from the paper "A Gentle Introduction to Conformal Prediction and
Distribution-Free Uncertainty Quantification" by Angelopoulos and Bates.

Dataset: Iris
Model: Support Vector Machine (SVM)
Language: R

## Structure
- `data/`: For datasets.
- `R/`: Contains R scripts for data loading, SVM modeling, conformal prediction logic, evaluation, and experiment execution.
- `results/`: For storing plots and tables generated by the experiments.